name: screenshots ci actions master
on:
  push:
    branches:
    - master

jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: mkdir -p screenshots/basic
    - run: mkdir -p screenshots/basic_mobile
    - run: mkdir -p screenshots/default_type
    - run: mkdir -p screenshots/png_type
    - run: mkdir -p screenshots/fullPage

    - name: install puppeteer-headful
      uses: mujo-code/puppeteer-headful@master
      env:
        CI: 'true'
    - name: Test no url
      uses: flameddd/screenshots-ci-action@master
    - name: Test desktop only
      uses: flameddd/screenshots-ci-action@master
      with:
        url: https://github.com
    - uses: actions/upload-artifact@v2
      with:
        name: Download-desktop-screenshots
        path: screenshots/basic
    - name: Test desktop and devices
      uses: flameddd/screenshots-ci-action@master
      with:
        url: https://github.com
        devices: iPhone 6,iPhone 6 landscape,Nexus 7,Pad Pro,Galaxy S III landscape
    - uses: actions/upload-artifact@v2
      with:
        name: Download-desktop-mobile-screenshots
        path: screenshots/basic_mobile
    - name: Test wrong type (default jpeg)
      uses: flameddd/screenshots-ci-action@master
      with:
        url: https://github.com
        noDesktop: true
        devices: iPhone 6
        type: aaa
    - uses: actions/upload-artifact@v2
      with:
        name: Download-mobile-wrong-type-screenshots
        path: screenshots/default_type
    - name: Test png type
      uses: flameddd/screenshots-ci-action@master
      with:
        url: https://github.com
        noDesktop: true
        devices: iPhone 6
        type: png
    - uses: actions/upload-artifact@v2
      with:
        name: Download-mobile-png-screenshots
        path: screenshots/png_type
    - name: Test fullPage
      uses: flameddd/screenshots-ci-action@master
      with:
        url: https://github.com
        noDesktop: true
        devices: iPhone 6
        fullPage: true
    - uses: actions/upload-artifact@v2
      with:
        name: Download-mobile-fullPage-screenshots
        path: screenshots/fullPage
