name: screenshots ci actions
on:
  push:
    branches:
    - master

jobs:
  screenshots:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: screenshots-ci-action
      uses: flameddd/screenshots-ci-action@v1.0.0
    - run: npm ci	
    - uses: ./
      with:
        url: https://github.com
        devices: iPhone 6,iPhone 6 landscape,Nexus 7,Pad Pro,Galaxy S III landscape,iPad Pro landscape
    - uses: actions/upload-artifact@v1
      with:
        name: Download-screenshots
        path: screenshots