name: screenshots ci actions master
on:
  push:
    branches:
    - master

jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: install puppeteer-headful
      uses: mujo-code/puppeteer-headful@master
      env:
        CI: 'true'
    - name: Test no url
      uses: flameddd/screenshots-ci-action@master
    - name: Test desktop only
      uses: flameddd/screenshots-ci-action@master
      with:
        url: https://twitter.com/
    - uses: actions/upload-artifact@v2
      with:
        path: screenshots
        name: Download-desktop-screenshots
    - run: rm ./screenshots/*

    - name: Test desktop and devices
      uses: flameddd/screenshots-ci-action@master
      with:
        url: https://twitter.com/
        devices: iPhone 6,iPhone 6 landscape,Nexus 7,Pad Pro,Galaxy S III landscape
    - uses: actions/upload-artifact@v2
      with:
        path: screenshots
        name: Download-desktop-mobile-screenshots
    - run: rm ./screenshots/*

    - name: Test wrong type (default jpeg)
      uses: flameddd/screenshots-ci-action@master
      with:
        url: https://twitter.com/
        noDesktop: true
        devices: iPhone 6
        type: aaa
    - uses: actions/upload-artifact@v2
      with:
        path: screenshots
        name: Download-mobile-wrong-type-screenshots
    - run: rm ./screenshots/*

    - name: Test png type
      uses: flameddd/screenshots-ci-action@master
      with:
        url: https://twitter.com/
        noDesktop: true
        devices: iPhone 6
        type: png
    - uses: actions/upload-artifact@v2
      with:
        path: screenshots
        name: Download-mobile-png-screenshots
    - run: rm ./screenshots/*

    - name: Test fullPage
      uses: flameddd/screenshots-ci-action@master
      with:
        url: https://twitter.com/
        noDesktop: true
        devices: iPhone 6
        fullPage: true
    - uses: actions/upload-artifact@v2
      with:
        path: screenshots
        name: Download-mobile-fullPage-screenshots
    - run: rm ./screenshots/*
